title = "My site"
base_url = "https://replace-this-with-your-url.com"
highlight_code = true
compile_sass = true
generate_rss = true
theme = "sample"

taxonomies = [
    {name = "categories", rss = true},
]

extra_syntaxes = ["syntaxes"]

ignored_content = ["*/ignored.md"]

link_checker_skip_anchor_prefixes = [
    "https://github.com/rust-lang/rust/blob/",
]

[extra.author]
name = "Vincent Prouillet"
